# Generated by Django 5.0.1 on 2024-07-11 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sotuv',
            name='otish',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='sotuv',
            name='tara',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
