# Generated by Django 5.0.1 on 2024-08-12 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_sotuv_otish_alter_sotuv_tara'),
    ]

    operations = [
        migrations.AddField(
            model_name='sotuv',
            name='foyda',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='sotuv',
            name='narxi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sotuv',
            name='meva_turi',
            field=models.CharField(choices=[('SUPER', 'SUPER'), ('LOLA 1', 'LOLA 1'), ('LOALA 2', 'LOLA 2'), ('pishgan', 'pishgan')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sotuv',
            name='otish',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
