# Generated by Django 5.0.1 on 2024-08-12 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_sotuv_foyda_sotuv_narxi_alter_sotuv_meva_turi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sotuv',
            name='narxi',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
