# Generated by Django 5.0.1 on 2024-08-12 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_alter_sotuv_narxi'),
    ]

    operations = [
        migrations.AddField(
            model_name='sotuv',
            name='umumiy_kilogram',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sotuv',
            name='tara',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0.5)]),
        ),
    ]
