# Generated by Django 5.0.1 on 2024-08-12 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_sotuv_umumiy_kilogram_alter_sotuv_tara'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sotuv',
            old_name='umumiy_kilogram',
            new_name='quti_ogirligi',
        ),
        migrations.AlterField(
            model_name='sotuv',
            name='otish',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sotuv',
            name='tara',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.5)]),
        ),
    ]
