# Generated by Django 5.0.1 on 2024-08-12 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_rename_umumiy_kilogram_sotuv_quti_ogirligi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sotuv',
            name='otish',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sotuv',
            name='quti_ogirligi',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
