# Generated by Django 5.0.1 on 2024-08-12 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_alter_sotuv_otish_alter_sotuv_quti_ogirligi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sotuv',
            name='otish',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
