# Generated by Django 5.0.1 on 2024-10-28 07:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_alter_sotuv_otish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MevaTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='sotuv',
            name='otish',
        ),
        migrations.RemoveField(
            model_name='sotuv',
            name='tara',
        ),
        migrations.AddField(
            model_name='sotuv',
            name='umumiy_ogirlik',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sotuv',
            name='quti_ogirligi',
            field=models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.5)]),
        ),
        migrations.AlterField(
            model_name='sotuv',
            name='quti_soni',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='sotuv',
            name='bog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.bog'),
        ),
        migrations.AlterField(
            model_name='sotuv',
            name='meva_turi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.mevaturi'),
        ),
    ]
