# Generated by Django 5.0.1 on 2024-10-28 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_bog_mevaturi_remove_sotuv_otish_remove_sotuv_tara_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xarajatlar',
            name='umumiy_xarajat',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
