# Generated by Django 5.0.1 on 2024-10-28 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_alter_xarajatlar_umumiy_xarajat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xarajatlar',
            name='umumiy_xarajat',
            field=models.IntegerField(help_text='Manfiy qiymat kiritmang ', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
