# Generated by Django 5.0.1 on 2024-10-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_alter_sotuv_quti_ogirligi'),
    ]

    operations = [
        migrations.AddField(
            model_name='bog',
            name='izoh',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='mevaturi',
            name='izoh',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
