# Generated by Django 5.0.1 on 2024-10-28 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_bog_izoh_mevaturi_izoh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mevaturi',
            name='izoh',
        ),
    ]
