# Generated by Django 5.0.1 on 2024-10-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_remove_mevaturi_izoh'),
    ]

    operations = [
        migrations.AddField(
            model_name='mevaturi',
            name='turi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
