# Generated by Django 5.0.1 on 2024-10-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_mevaturi_turi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bog',
            options={'verbose_name_plural': 'Bog'},
        ),
    ]
