# Generated by Django 5.0.1 on 2024-10-28 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_alter_bog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xarajatlar',
            options={'verbose_name': 'Xarajatlars', 'verbose_name_plural': 'Xarajatlar'},
        ),
    ]
