# Generated by Django 5.0.1 on 2024-10-28 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0020_alter_mevaturi_options_alter_sotuv_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bog',
            options={'verbose_name_plural': "Boglar ro'yhati"},
        ),
    ]
