# Generated by Django 5.0.1 on 2024-10-28 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0021_alter_bog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sotuv',
            name='foyda',
            field=models.BigIntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
